export const listProgramSNBT_UTBK = [
  "Les Privat UTBK SNBT",
  "Les Privat Simak UI",
  "Les Privat Simak KKI",
  "Les Privat Simak S2/S3/PPDS/Spesialis 2",
  "Les Privat IUP UGM",
  "Les Privat UTUL UGM",
  "Les Privat SM ITB",
  "Les Privat IUP ITB",
  "Les Privat SM ITS",
  "Les Privat IUP ITS",
  "Les Privat UM UNDIP",
  "Les Privat IUP Undip",
  "Les Privat UM Unair",
  "Les Privat IUP Unair",
  "Les Privat SMUP Unpad",
  "Les Privat SM-IPB",
  "Les Privat Penmaba UNJ",
  "Les Privat UM UNS",
  "Les Privat SEMA UPNVJ",
  "Les Privat UM UNHAS",
];
